name: Node.js Package
env:
  production: true
  
on:
  release:
    types: [created]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Run ci
        run: npm ci

      - name: Run tests
        run: npm test
